services:
  shelfgo:
    build: .
    container_name: shelfgo
    environment:
      - SHELFGO_USER=${SHELFGO_USER}
      - SHELFGO_PASS=${SHELFGO_PASS}
      - SHELFGO_PORT=${SHELFGO_PORT}
      - SHELFGO_DIR=${SHELFGO_DIR}
    volumes:
      - ./ebooks:/ebooks
    restart: unless-stopped
    ports:
      - ${SHELFGO_PORT}:${SHELFGO_PORT}
    depends_on:
      - cloudflared

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: shelfgo-cloudflared
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CF_TOKEN}
    restart: unless-stopped
